_base: &base_collator
  _target_: src.collators.base_collator.BaseCollator
  max_length: 256
  truncation: true
  padding: max_length
  return_tensors: pt
  tokenizer:
    _target_: transformers.AutoTokenizer.from_pretrained
    pretrained_model_name_or_path: ${llm.model_loading.pretrained_model_name_or_path}
train: *base_collator
test: *base_collator
generate:
  _target_: src.collators.generation_collator.GenerationCollator
